platform:
- x86
- x64
environment:
    PYTHON: "C:\\Python27"
version: 1.0.{build}
os: Visual Studio 2015
install:
  - SET "PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - easy_install scons
build_script:
- scons --version
- scons install
- '@echo off'
- setlocal
- ps: >-
    If ($env:Platform -Match "x86") {
      $env:VCVARS_PLATFORM="x86"
    } Else {
      $env:VCVARS_PLATFORM="amd64"
    }
- call "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" %VCVARS_PLATFORM%
- call tools\windows\build.bat
- call tools\windows\build_examples.bat
- exit /b 0
